version: "3.8"

services:
  flower:
    image: flower
    container_name: flower
    env_file: env/local.env
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      init_backend:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: docker/flower.Dockerfile
    ports:
      - 5555:5555

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pa55word
    env_file: env/local.env
    networks:
      - backend
    ports:
      - 5050:80
    depends_on:
      init_backend:
        condition: service_completed_successfully